name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: thebanker
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/debug/app-debug.apk
          asset_name: thebanker
          tag: ${{ github.ref }}
          overwrite: false
          body: "This is my latest release of the banker app"

#  publish:
#      name: Publish binaries
#      runs-on: ubuntu-latest
#      needs: apk
#
#      steps:
#        - name: Download a single artifact
#          uses: actions/download-artifact@v2
#          with:
#            name: thebanker
#        - name: Upload binaries to release
#          uses: svenstaro/upload-release-action@v2
#          with:
#            repo_token: ${{ secrets.GITHUB_TOKEN }}
#            file: thebanker
#            asset_name: thebanker
#            tag: ${{ github.ref }}
#            overwrite: true
#            body: "This is my latest release of the banker app"