name: Android CD

on:
  push:
    tags:
      -'*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "theBanker"
          allowUpdates: true
          body: "You can use this build to see to latest implementation of the app"
          name: "The Banker App "
          token: ${{ secrets.f041dbaf41a2da168df340280abaf1711f92c9f1 }}