name: Releases

on:
  push:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          body: "body.md"
          token: ${{ secrets.f041dbaf41a2da168df340280abaf1711f92c9f1 }}